name: docs

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Run
      run: |
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh |
            bash -s -- --batch
        conda env create --file environment.yml
        conda run --name aizynthfinder poetry install
        conda run --name aizynthfinder poe document
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html
        publish_branch: gh-pages
        force_orphan: true
