name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run
      run: |
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        chmod +x $(basename $_) && ./$_ -b
        conda env create --file environment.yml
        conda activate aizynthfinder
        poetry config --local settings.virtualenvs.create false
        poetry install
        poe test
